export interface Cars {
    id: number;
    marca: string;
    modelo: string;
    version: string;
    tipo_ev: string;
    precio_lista: number;
    rango_wltp: number | null;
    bateria_nominal: number | null;
    potencia: number;
    potencia_kw: number;
    is_electric: boolean;
    is_hybrid: boolean;
    consumo_electrico: number | null;
    consumo: number | null;
    created_at: Date;
}

export interface CarDetails {
    id: number;
    potencia_kw: number;
    efficiency_kwh_per_100km: null;
    autonomia_combustible: number;
    autonomia_combinada: null;
    consumo_electrico: null;
    consumo_diario: null;
    consumo_comparable: null;
    tiempo_carga_20_80_ac: null;
    tiempo_carga_20_80_dc: null;
    autonomia_80_20_carga: null;
    is_electric: boolean;
    is_hybrid: boolean;
    marca_modelo: string;
    has_charging_capability: boolean;
    car_brand_logo: string;
    marca: string;
    modelo: string;
    version: string;
    carroceria: string;
    tipo_ev: string;
    ficha_tecnica: null;
    precio_lista: number;
    rango_wltp: null;
    bateria_nominal: null;
    traccion: null;
    transmision: null;
    potencia: number;
    torque: number;
    aceleracion: number;
    maxima_velocidad: number;
    motor_combustion: number;
    estanque_combustible: number;
    consumo: number;
    tipo_bateria: null;
    tipo_carga_ac: null;
    carga_ac: null;
    tipo_carga_dc: null;
    carga_dc_max: null;
    peso: number;
    largo: number;
    ancho: number;
    alto: number;
    distancia_entre_ejes: number;
    maletero: number;
    llantas: number;
    asientos: number;
    airbags: number;
    seguridad_ncap: number;
    garantia_anos: number;
    garantia_km: number;
    inicio_produccion: number;
    popularity: null;
    logo_urls: string[];
    foto_portada: null;
    created_at: Date;
    updated_at: Date;
    car_raw: number;
    car_brand: number;
}
